### ISSUE TITLE
CSS modules

### ISSUE THREAD

**Issue by dgp1130** [dgp1130/rules_prerender#37]
I'm wondering if we can rework CSS support to use a DX closer to [CSS Modules](https://css-tricks.com/css-modules-part-1-need/). This might be a more standardized from of using CSS. Consider:

```typescript
import styles from './styles.css';

export function renderComponent(): string {
    return `
        <div class="${styles.firstClass}"></div>
        <div class="${styles.secondClass}"></div>
    `;
}
```

```css
.firstClass {
    color: red;
}

.secondClass {
    color: blue;
}
```

This would give style isolation for components and still be technically tree-shakable.
